### ISSUE TITLE
[Feature Request] Custom Low Battery Notification Sounds

### ISSUE THREAD

**Issue by TheLastRar** [Curtis-VL/OVRToolkit-Issues#58] opened 2022-01-19 23:53 UTC
As above, can we get the option change the low battery notification sounds

I want to be able to specify it by selecting or copying a file, but steam workshop support would also be nice

**Comment by Curtis-VL** [comment] 2022-01-19 23:54
Duplicate of #37!
Plan to work on this but it's rather low priority at the moment. :)

**Closed by Curtis-VL** 2022-01-19 23:54 UTC

**Comment by TheLastRar** [comment] 2022-01-19 23:57
Sorry, I only looked though issues tagged with Feature Request, I didn't see the whislist tag
