### ISSUE TITLE
Wristwatch battery % is both in % and in minutes

### ISSUE THREAD

**Issue by fwenny** [Curtis-VL/OVRToolkit-Issues#82] opened 2022-02-13 06:16 UTC
Hi. Apologies if this bug has been reported already.
![bug](https://user-images.githubusercontent.com/44194453/153741305-3de88b40-b77a-4bc2-85da-ac9b01b548e2.png)

I have "show battery level in minutes" disabled in options, but it appears like the wristwatch cant decide which one to choose (showing both of them)

**Comment by Curtis-VL** [comment] 2022-02-13 15:08
Oh right!

Technically not a bug, when battery minutes remaining is below 10 minutes it starts to show in minutes as a final warning.

I should probably change this to show only percent though now that the option exists. :)

**Comment by fwenny** [comment] 2022-02-13 15:43
Ah, I understand.
But yes, it would be great if it was more consistent.

**Comment by ThizThizzyDizzy** [comment] 2022-02-13 18:08
> when battery minutes remaining is below 10 minutes it starts to show in minutes as a final warning.

Strange, it never does that for me. Would clicking it to cycle modes bypass this?

**Comment by Curtis-VL** [comment] 2022-02-13 18:21
> > when battery minutes remaining is below 10 minutes it starts to show in minutes as a final warning.
> 
> Strange, it never does that for me. Would clicking it to cycle modes bypass this?

It's only when display in minutes is turned off. It's a legacy feature from before I added the option to display remaining time constantly like is now the default. :)

**Comment by Curtis-VL** [comment] 2022-02-15 00:43
Having thought about this a little, I'd say this is intended behaviour so I'll close the issue!

I think more people will find it showing minutes when at critical battery more useful than percentage. :)

**Closed by Curtis-VL** 2022-02-15 00:43 UTC
Labels: bug
