### ISSUE TITLE
Virtual keyboard shift gets randomly stuck for 20 seconds

### ISSUE THREAD

**Issue by fwenny** [Curtis-VL/OVRToolkit-Issues#81] opened 2022-02-08 15:26 UTC
Hi. I was wondering if this issue has been reported in the past?
I honestly dont know how to reproduce it, but sometimes while typing, clicking SHIFT will freeze the keyboard in a way, where you cannot click on any of the letters.
You can interact with other modifiers like ctrl and alt, but the letters become unavailable for 20-30 seconds.

**Comment by fwenny** [comment] 2022-02-08 15:39
the keyboard isnt frozen per say. i can still move it around and interact with a couple buttons, but specifically the buttons that get affected by the shift buttons (ie letters become capital, and numbers turn into their respective symbols) become unresponsive.

i never had it stick in a way where it is constantly on though

**Comment by Curtis-VL** [comment] 2022-02-08 16:25
I've had this happen too. I'm not sure how to reproduce it though to find any causes.

I think I have a thought about the cause though.

**Comment by nullstalgia** [comment] 2022-02-08 20:46
This is a new issue I've also come across, but I assumed it was a bug with the custom keyboard I use (US Physical) so I didn't report it.

**Comment by Curtis-VL** [comment] 2022-02-08 20:48
> This is a new issue I've also come across, but I assumed it was a bug with the custom keyboard I use (US Physical) so I didn't report it.

Hold up, you had it on the physical keyboard? I don't think this dynamically moves keys.

Maybe this points to an issue with the interaction system I'm using, maybe it's ignoring keys for some reason as it things they're duplicates or something. I'll dig into it.

**Comment by nullstalgia** [comment] 2022-02-08 20:57
> Hold up, you had it on the physical keyboard? I don't think this dynamically moves keys.

Yeah, the Shift key would click in, and just not highlight or respond to inputs for around 20 seconds, which lines up to the issue's title here. I would move my hands all over the place trying to get off the keyboard, then back on, then eventually it would just come back and work normally. I don't know if it would make more typed text "Shifted," since I was too busy trying to make it work again than type more.

**Comment by Curtis-VL** [comment] 2022-02-08 21:08
Potential fix implemented for today's closed beta, if you could, let me know if it happens again tomorrow onwards!

**Comment by fwenny** [comment] 2022-02-08 23:11
sorry to be off topic but ovr toolkit has a physical keyboard?
and ty, will check it, though seeing as it only happens once in a while, would be difficult to test

**Comment by Curtis-VL** [comment] 2022-02-08 23:11
Through the Workshop it does yeah.

Though, I will note that my implemented fix in the Open and Closed Beta is specific to the default keyboard!

**Comment by fwenny** [comment] 2022-02-08 23:16
does physical mean i can tap my finger tips on the keys to use it?

**Comment by Curtis-VL** [comment] 2022-02-08 23:17
Oh no! Physical as in it's got the F keys, Numpad, etc. - Full sized keyboard like you might have 'physically' outside of VR. :)

Not possible to do hand interaction due to no way to display your hand.

**Comment by fwenny** [comment] 2022-02-08 23:17
ohh okay sorry for the misunderstanding. xD
next time i play ill get on the closed beta and see if the bug happens again.

**Comment by fwenny** [comment] 2022-02-24 06:56
still happens unfortunately.
however toggling caps lock on and off fixes it.

**Comment by Curtis-VL** [comment] 2022-02-24 13:28
> 

To double check, you mean with the default keyboard? Not a custom one?

**Comment by fwenny** [comment] 2022-02-24 14:53
yep, I reverted back to the original keyboard with the rest option in settings

**Comment by Curtis-VL** [comment] 2022-05-24 20:50
Attempted a fix for this yet again! Re-wrote the keyboard input logic from scratch, though as I don't know the cause of this issue yet, it's entirely possible it still exists!

Lets hope it's fixed though! I'll close this for now, let me know if it still persists after the next public release. Currently in open and closed beta branches. :)

**Closed by Curtis-VL** 2022-05-24 20:50 UTC
Labels: bug
